title: Shaonan Wu's Homepage
description: Shaonan Wu's Homepage

header:
  pages:
    - name: Home
      slug: /

footer:
  show_powered_by: False
  follow:
    - type: github
      name: GitHub
      link: http://github.com/wclsn
    - type: 

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
